name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      
      - name: Install dependencies
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.add(["Documenter", "DocumenterVitepress"]);
            Pkg.instantiate();
            Pkg.precompile();
          '
      
      - name: Build documentation
        run: julia --project=. make.jl
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name != 'pull_request'
        with:
          folder: build
          branch: gh-pages
          clean: true